set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports flash]
set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports load_div]
set_property PACKAGE_PIN R17 [get_ports enable]
set_property PACKAGE_PIN N20 [get_ports flash]
set_property PACKAGE_PIN U20 [get_ports load_div]
set_property PACKAGE_PIN T14 [get_ports {div_count[3]}]
set_property PACKAGE_PIN T11 [get_ports {div_count[2]}]
set_property PACKAGE_PIN T12 [get_ports {div_count[1]}]
set_property PACKAGE_PIN T10 [get_ports {div_count[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {div_count[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {div_count[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {div_count[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {div_count[3]}]
set_property PACKAGE_PIN H16 [get_ports clock]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 4} [get_ports { clock }];